---

- hosts: all
  become: true
  pre_tasks:

  - name: update repo cache (CentOS)
    dnf:
      update_cache: yes
    when: ansible_distribution == "CentOS"

  - name: update repo cache (Ubuntu)
    apt:
      update_cache: yes
    when: ansible_distribution == "Ubuntu"

- hosts: web_servers
  become: true
  roles:
  - web_servers

