- name: install web server packages
  package:
    name:
      - "{{ apache_package_name }}"
      - "{{ php_package_name }}"
    state: latest

- name: start and enable apache service
  service:
    name: "{{ apache_service }}"
    state: started
    enabled: yes

- name: Create firewall rule for apache service
  ansible.posix.firewalld:
    service: http
    permanent: yes
    immediate: yes
    state: enabled
  when: ansible_distribution == "CentOS"

- name: copy html file for site
  template:
    src: default_site.j2
    dest: /var/www/html/index.html
    owner: root
    group: root
    mode: 0644

- name: start and enable apache service
  service:
    name: "{{ apache_service }}"
    state: restarted